project:
  type: website
  output-dir: docs

website:
  title: "Zachariah Marrero PhD"
  twitter-card: true
  open-graph: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: AcceleratedStatsLearning.qmd
        text: Accelerated Statistics

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

