---
title: "Website Overview"
css: about.css
id: about_text
toc: false
---

::: {#about_text}
## **Keeping it short and simple...**

This website is a place where I will share how to do things with data.

At the top of the page you can currently see the words 'Accelerated Statistics.' The content within covers some very basic, yet very important, lessons for statistical analysis. Feel free to take a break from the current conversations about AI to review the contents here. You will be surprised at the fun you can have once you understand the tools within.

There is also a 'XGBoost Scripts (Free)' page. These scripts are an excellent resource you can use to study and experiment with ML. With a little bit of extension, they could easily be adapted for a production ready environment. 

In my next post, I will show how to host your very own instance of open-source Large Language Models. The landscape is changing rapidly with these tools and there is already exciting work shrinking both their size and required compute resources. At the extreme, some models have already been squeezed on to Raspberry pi. In any case, a significant ongoing need is more research on model capabilities. In particular, to better understand their capabilities models need to be evaluated on real world research problems where the researcher has domain expertise and can manipulate the problem to study the models. So, hosting your own model will give you the ability to conduct research in a completely safe environment and to explore the use of these tools which have taken control of most of the conversation in AI today. 

Later on, I will make more posts that utilize the principles outlined in Accelerated Statistics for the presentation and evaluation of popular machine learning algorithms in the weeks, months, and years ahead. I will also continue the work on Acclerated Statisics as outlined in its concluding section. And so so so much more... 

I'm (still) currently sitting on a mountain of notes that I've accumulated over the course of my PhD studies (If you want to appreciate the flavor of this work, you can find my dissertation currently through my linkedin in the projects section). I will share methods and materials on how to approach the study of machine learning algorithms. Broadly speaking, algorithms are not built to have the same capabilities. Yet there is currently relatively little work demonstrating the properties of them. In some cases the math is still being discovered and in other cases the discoveries need to be translated for greater accessibility. Fortunately, classical statistics provides us with a roadmap for how we can approach the evaluation of algorithms in the most general sense AND modern computers make it possible.

:::
