project:
  type: website
  output-dir: .
 
website:
  title: "Zachariah Marrero PhD"
  twitter-card: true
  open-graph: true
  navbar:
    left:
      - href: Navbar pages/home_page.qmd
        text: Home
      - href: Navbar pages/about.qmd
        text: About
      - href: Navbar pages/AcceleratedStatsLearning.qmd
        text: Accelerated Statistics
      - href: Navbar pages/XGBoost_page.qmd
        text: XGBoost scripts (FREE)
     
    right: 
      - text: "Toggle Dark/Light:"

format:
  html:
    theme: 
      light: [cosmo, styles_light.css]
      dark: [cosmo, styles_dark.css]
    css: styles_light.css
    toc: true
 

editor: visual



