project:
  type: website
  output-dir: .
 
website:
  title: "Zachariah Marrero PhD"
  twitter-card: true
  open-graph: true
  navbar:
    left:
      - href: Navbar pages/home_page.qmd
        text: Home
      - href: Navbar pages/about.qmd
        text: About
      - href: Navbar pages/AcceleratedStatsLearning.qmd
        text: Accelerated Statistics

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual


